// Code generated by pg_generator. DO NOT EDIT.

package appconfig

import (
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"iter"
	"strings"
)

// Generated CRUD operations for aws_login_attachments

const findLimitAttachment = 50

// AttachmentFilter represents filter options for Attachment queries
type AttachmentFilter struct {
	SourceId *string
	TargetId *string
	AttachmentType *string
}


// decodeToken decodes a base64-encoded offset token
func (a *Attachment) decodeToken(token string) (int, error) {
	if token == "" {
		return 0, nil
	}
	data, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return 0, err
	}
	var offset int
	fmt.Sscanf(string(data), "%d", &offset)
	return offset, nil
}


// Get retrieves a Attachment by ID
func (a *Attachment) Get(ctx context.Context, db *sql.DB, sourceid string, targetid string, attachmenttype string) error {
	var whereClauses []string
	var args []any
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "source_id", 1))
	args = append(args, sourceid)
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "target_id", 2))
	args = append(args, targetid)
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "attachment_type", 3))
	args = append(args, attachmenttype)

	q := fmt.Sprintf("SELECT source_id, target_id, attachment_type, created_by, created_time FROM aws_login_attachments WHERE %s", strings.Join(whereClauses, " AND "))

	return db.QueryRowContext(ctx, q, args...).Scan(
		&a.SourceId,
		&a.TargetId,
		&a.AttachmentType,
		&a.CreatedBy,
		&a.CreatedTime,
	)
}

// Delete deletes a Attachment by ID
func (a *Attachment) Delete(ctx context.Context, db *sql.DB, sourceid string, targetid string, attachmenttype string) error {
	var whereClauses []string
	var args []any
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "source_id", 1))
	args = append(args, sourceid)
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "target_id", 2))
	args = append(args, targetid)
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "attachment_type", 3))
	args = append(args, attachmenttype)

	q := fmt.Sprintf("DELETE FROM aws_login_attachments WHERE %s", strings.Join(whereClauses, " AND "))
	_, err := db.ExecContext(ctx, q, args...)
	return err
}


// Insert inserts a Attachment into the database
func (a *Attachment) Insert(ctx context.Context, db *sql.DB) error {
	columns := []string{ "source_id","target_id","attachment_type","created_by","created_time", }
	placeholders := make([]string, len(columns))
	for i := range columns {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}

	q := fmt.Sprintf("INSERT INTO aws_login_attachments (%s) VALUES (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))

	_, err := db.ExecContext(ctx, q,
		a.SourceId,
		a.TargetId,
		a.AttachmentType,
		a.CreatedBy,
		a.CreatedTime,
	)
	return err
}

// Update updates a Attachment in the database
func (a *Attachment) Update(ctx context.Context, db *sql.DB) error {
	setClauses := make([]string, 0, 5)
	args := make([]any, 0, 8)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "created_by", 4))
	args = append(args, a.CreatedBy)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "created_time", 5))
	args = append(args, a.CreatedTime)

	idArgs := make([]any, 0, 3)
	idArgs = append(idArgs, a.SourceId)
	idArgs = append(idArgs, a.TargetId)
	idArgs = append(idArgs, a.AttachmentType)
	args = append(args, idArgs...)

	whereClauses := make([]string, 0, 3)
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "source_id", 6))
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "target_id", 7))
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "attachment_type", 8))

	q := fmt.Sprintf("UPDATE aws_login_attachments SET %s WHERE %s", strings.Join(setClauses, ", "), strings.Join(whereClauses, " AND "))
	_, err := db.ExecContext(ctx, q, args...)
	return err
}

// List returns all Attachment rows
func (a *Attachment) List(ctx context.Context, db *sql.DB) iter.Seq2[*Attachment, error] {
	return func(yield func(*Attachment, error) bool) {
		q := fmt.Sprintf("SELECT source_id, target_id, attachment_type, created_by, created_time FROM aws_login_attachments ORDER BY 1")
		rows, err := db.QueryContext(ctx, q)
		if err != nil {
			yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			var item Attachment
			if err := rows.Scan(
				&item.SourceId,
				&item.TargetId,
				&item.AttachmentType,
				&item.CreatedBy,
				&item.CreatedTime,
			); err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if !yield(&item, nil) {
				return
			}
		}
	}
}

// Find returns Attachment rows matching the filter with pagination
func (a *Attachment) Find(ctx context.Context, db *sql.DB, filter AttachmentFilter, token string) ([]*Attachment,*string, error) {
	offset, err := a.decodeToken(token)
	if err != nil {
		return nil, nil, fmt.Errorf("decode token: %w", err)
	}

	var conditions []string
	var args []any
	if filter.SourceId != nil {
		args = append(args, *filter.SourceId)
		conditions = append(conditions, fmt.Sprintf("%s = $%d", "source_id", len(args)))
	}
	if filter.TargetId != nil {
		args = append(args, *filter.TargetId)
		conditions = append(conditions, fmt.Sprintf("%s = $%d", "target_id", len(args)))
	}
	if filter.AttachmentType != nil {
		args = append(args, *filter.AttachmentType)
		conditions = append(conditions, fmt.Sprintf("%s = $%d", "attachment_type", len(args)))
	}

	where := ""
	if len(conditions) > 0 {
		where = " WHERE " + strings.Join(conditions, " AND ")
	}

	q := fmt.Sprintf("SELECT source_id, target_id, attachment_type, created_by, created_time FROM aws_login_attachments%s ORDER BY 1 OFFSET %d LIMIT %d", where, offset, findLimitAttachment)

	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("query: %w", err)
	}
	defer rows.Close()

	var items []*Attachment
	for rows.Next() {
		var item Attachment
		if err := rows.Scan(
			&item.SourceId,
			&item.TargetId,
			&item.AttachmentType,
			&item.CreatedBy,
			&item.CreatedTime,
		); err != nil {
			return nil, nil, fmt.Errorf("scan: %w", err)
		}
		items = append(items, &item)
	}

	nextToken := ""
	if len(items) == findLimitAttachment {
		nextOffset := offset + findLimitAttachment
		nextToken = base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", nextOffset)))
	}

	return items, &nextToken, nil
}
