// Code generated by pg_generator. DO NOT EDIT.

package appconfig

import (
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"iter"
	"strings"
)

// Generated CRUD operations for aws_login_roles

const findLimitRole = 50

// RoleFilter represents filter options for Role queries
type RoleFilter struct {
}


// decodeToken decodes a base64-encoded offset token
func (a *Role) decodeToken(token string) (int, error) {
	if token == "" {
		return 0, nil
	}
	data, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return 0, err
	}
	var offset int
	fmt.Sscanf(string(data), "%d", &offset)
	return offset, nil
}



// Insert inserts a Role into the database
func (a *Role) Insert(ctx context.Context, db *sql.DB) error {
	columns := []string{ "name","managed_policies","max_session_duration","created_by","created_time","updated_by","update_time", }
	placeholders := make([]string, len(columns))
	for i := range columns {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}

	q := fmt.Sprintf("INSERT INTO aws_login_roles (%s) VALUES (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))

	_, err := db.ExecContext(ctx, q,
		a.Name,
		a.ManagedPolicies,
		a.MaxSessionDuration,
		a.CreatedBy,
		a.CreatedTime,
		a.UpdatedBy,
		a.UpdateTime,
	)
	return err
}

// Update updates a Role in the database
func (a *Role) Update(ctx context.Context, db *sql.DB) error {
	return fmt.Errorf("Update requires at least one field with db:id tag")
}

// List returns all Role rows
func (a *Role) List(ctx context.Context, db *sql.DB) iter.Seq2[*Role, error] {
	return func(yield func(*Role, error) bool) {
		q := fmt.Sprintf("SELECT name, managed_policies, max_session_duration, created_by, created_time, updated_by, update_time FROM aws_login_roles ORDER BY 1")
		rows, err := db.QueryContext(ctx, q)
		if err != nil {
			yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			var item Role
			if err := rows.Scan(
				&item.Name,
				&item.ManagedPolicies,
				&item.MaxSessionDuration,
				&item.CreatedBy,
				&item.CreatedTime,
				&item.UpdatedBy,
				&item.UpdateTime,
			); err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if !yield(&item, nil) {
				return
			}
		}
	}
}

// Find returns Role rows matching the filter with pagination
func (a *Role) Find(ctx context.Context, db *sql.DB, filter RoleFilter, token string) ([]*Role,*string, error) {
	offset, err := a.decodeToken(token)
	if err != nil {
		return nil, nil, fmt.Errorf("decode token: %w", err)
	}

	var conditions []string
	var args []any

	where := ""
	if len(conditions) > 0 {
		where = " WHERE " + strings.Join(conditions, " AND ")
	}

	q := fmt.Sprintf("SELECT name, managed_policies, max_session_duration, created_by, created_time, updated_by, update_time FROM aws_login_roles%s ORDER BY 1 OFFSET %d LIMIT %d", where, offset, findLimitRole)

	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("query: %w", err)
	}
	defer rows.Close()

	var items []*Role
	for rows.Next() {
		var item Role
		if err := rows.Scan(
			&item.Name,
			&item.ManagedPolicies,
			&item.MaxSessionDuration,
			&item.CreatedBy,
			&item.CreatedTime,
			&item.UpdatedBy,
			&item.UpdateTime,
		); err != nil {
			return nil, nil, fmt.Errorf("scan: %w", err)
		}
		items = append(items, &item)
	}

	nextToken := ""
	if len(items) == findLimitRole {
		nextOffset := offset + findLimitRole
		nextToken = base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", nextOffset)))
	}

	return items, &nextToken, nil
}
