// Code generated by pg_generator. DO NOT EDIT.

package appconfig

import (
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"iter"
	"strings"
)

// Generated CRUD operations for aws_login_policies

const findLimitPolicy = 50

// PolicyFilter represents filter options for Policy queries
type PolicyFilter struct {
}


// decodeToken decodes a base64-encoded offset token
func (a *Policy) decodeToken(token string) (int, error) {
	if token == "" {
		return 0, nil
	}
	data, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return 0, err
	}
	var offset int
	fmt.Sscanf(string(data), "%d", &offset)
	return offset, nil
}



// Insert inserts a Policy into the database
func (a *Policy) Insert(ctx context.Context, db *sql.DB) error {
	columns := []string{ "id","document", }
	placeholders := make([]string, len(columns))
	for i := range columns {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}

	q := fmt.Sprintf("INSERT INTO aws_login_policies (%s) VALUES (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))

	_, err := db.ExecContext(ctx, q,
		a.Id,
		a.Document,
	)
	return err
}

// Update updates a Policy in the database
func (a *Policy) Update(ctx context.Context, db *sql.DB) error {
	return fmt.Errorf("Update requires at least one field with db:id tag")
}

// List returns all Policy rows
func (a *Policy) List(ctx context.Context, db *sql.DB) iter.Seq2[*Policy, error] {
	return func(yield func(*Policy, error) bool) {
		q := fmt.Sprintf("SELECT id, document FROM aws_login_policies ORDER BY 1")
		rows, err := db.QueryContext(ctx, q)
		if err != nil {
			yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			var item Policy
			if err := rows.Scan(
				&item.Id,
				&item.Document,
			); err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if !yield(&item, nil) {
				return
			}
		}
	}
}

// Find returns Policy rows matching the filter with pagination
func (a *Policy) Find(ctx context.Context, db *sql.DB, filter PolicyFilter, token string) ([]*Policy,*string, error) {
	offset, err := a.decodeToken(token)
	if err != nil {
		return nil, nil, fmt.Errorf("decode token: %w", err)
	}

	var conditions []string
	var args []any

	where := ""
	if len(conditions) > 0 {
		where = " WHERE " + strings.Join(conditions, " AND ")
	}

	q := fmt.Sprintf("SELECT id, document FROM aws_login_policies%s ORDER BY 1 OFFSET %d LIMIT %d", where, offset, findLimitPolicy)

	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("query: %w", err)
	}
	defer rows.Close()

	var items []*Policy
	for rows.Next() {
		var item Policy
		if err := rows.Scan(
			&item.Id,
			&item.Document,
		); err != nil {
			return nil, nil, fmt.Errorf("scan: %w", err)
		}
		items = append(items, &item)
	}

	nextToken := ""
	if len(items) == findLimitPolicy {
		nextOffset := offset + findLimitPolicy
		nextToken = base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", nextOffset)))
	}

	return items, &nextToken, nil
}
