// Code generated by pg_generator. DO NOT EDIT.

package appconfig

import (
	"context"
	"database/sql"
	"encoding/base64"
	"fmt"
	"iter"
	"strings"
)

// Generated CRUD operations for aws_login_users

const findLimitUser = 50

// UserFilter represents filter options for User queries
type UserFilter struct {
}


// decodeToken decodes a base64-encoded offset token
func (a *User) decodeToken(token string) (int, error) {
	if token == "" {
		return 0, nil
	}
	data, err := base64.StdEncoding.DecodeString(token)
	if err != nil {
		return 0, err
	}
	var offset int
	fmt.Sscanf(string(data), "%d", &offset)
	return offset, nil
}


// Get retrieves a User by ID
func (a *User) Get(ctx context.Context, db *sql.DB, name string) error {
	var whereClauses []string
	var args []any
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "name", 1))
	args = append(args, name)

	q := fmt.Sprintf("SELECT friendly_name, name, superuser, created_by, created_time, updated_by, update_time FROM aws_login_users WHERE %s", strings.Join(whereClauses, " AND "))

	return db.QueryRowContext(ctx, q, args...).Scan(
		&a.FriendlyName,
		&a.Name,
		&a.Superuser,
		&a.CreatedBy,
		&a.CreatedTime,
		&a.UpdatedBy,
		&a.UpdateTime,
	)
}

// Delete deletes a User by ID
func (a *User) Delete(ctx context.Context, db *sql.DB, name string) error {
	var whereClauses []string
	var args []any
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "name", 1))
	args = append(args, name)

	q := fmt.Sprintf("DELETE FROM aws_login_users WHERE %s", strings.Join(whereClauses, " AND "))
	_, err := db.ExecContext(ctx, q, args...)
	return err
}


// Insert inserts a User into the database
func (a *User) Insert(ctx context.Context, db *sql.DB) error {
	columns := []string{ "friendly_name","name","superuser","created_by","created_time","updated_by","update_time", }
	placeholders := make([]string, len(columns))
	for i := range columns {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}

	q := fmt.Sprintf("INSERT INTO aws_login_users (%s) VALUES (%s)", strings.Join(columns, ", "), strings.Join(placeholders, ", "))

	_, err := db.ExecContext(ctx, q,
		a.FriendlyName,
		a.Name,
		a.Superuser,
		a.CreatedBy,
		a.CreatedTime,
		a.UpdatedBy,
		a.UpdateTime,
	)
	return err
}

// Update updates a User in the database
func (a *User) Update(ctx context.Context, db *sql.DB) error {
	setClauses := make([]string, 0, 7)
	args := make([]any, 0, 8)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "friendly_name", 1))
	args = append(args, a.FriendlyName)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "superuser", 3))
	args = append(args, a.Superuser)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "created_by", 4))
	args = append(args, a.CreatedBy)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "created_time", 5))
	args = append(args, a.CreatedTime)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "updated_by", 6))
	args = append(args, a.UpdatedBy)
	setClauses = append(setClauses, fmt.Sprintf("%s = $%d", "update_time", 7))
	args = append(args, a.UpdateTime)

	idArgs := make([]any, 0, 1)
	idArgs = append(idArgs, a.Name)
	args = append(args, idArgs...)

	whereClauses := make([]string, 0, 1)
	whereClauses = append(whereClauses, fmt.Sprintf("%s = $%d", "name", 8))

	q := fmt.Sprintf("UPDATE aws_login_users SET %s WHERE %s", strings.Join(setClauses, ", "), strings.Join(whereClauses, " AND "))
	_, err := db.ExecContext(ctx, q, args...)
	return err
}

// List returns all User rows
func (a *User) List(ctx context.Context, db *sql.DB) iter.Seq2[*User, error] {
	return func(yield func(*User, error) bool) {
		q := fmt.Sprintf("SELECT friendly_name, name, superuser, created_by, created_time, updated_by, update_time FROM aws_login_users ORDER BY 1")
		rows, err := db.QueryContext(ctx, q)
		if err != nil {
			yield(nil, err)
			return
		}
		defer rows.Close()

		for rows.Next() {
			var item User
			if err := rows.Scan(
				&item.FriendlyName,
				&item.Name,
				&item.Superuser,
				&item.CreatedBy,
				&item.CreatedTime,
				&item.UpdatedBy,
				&item.UpdateTime,
			); err != nil {
				if !yield(nil, err) {
					return
				}
				continue
			}
			if !yield(&item, nil) {
				return
			}
		}
	}
}

// Find returns User rows matching the filter with pagination
func (a *User) Find(ctx context.Context, db *sql.DB, filter UserFilter, token string) ([]*User,*string, error) {
	offset, err := a.decodeToken(token)
	if err != nil {
		return nil, nil, fmt.Errorf("decode token: %w", err)
	}

	var conditions []string
	var args []any

	where := ""
	if len(conditions) > 0 {
		where = " WHERE " + strings.Join(conditions, " AND ")
	}

	q := fmt.Sprintf("SELECT friendly_name, name, superuser, created_by, created_time, updated_by, update_time FROM aws_login_users%s ORDER BY 1 OFFSET %d LIMIT %d", where, offset, findLimitUser)

	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("query: %w", err)
	}
	defer rows.Close()

	var items []*User
	for rows.Next() {
		var item User
		if err := rows.Scan(
			&item.FriendlyName,
			&item.Name,
			&item.Superuser,
			&item.CreatedBy,
			&item.CreatedTime,
			&item.UpdatedBy,
			&item.UpdateTime,
		); err != nil {
			return nil, nil, fmt.Errorf("scan: %w", err)
		}
		items = append(items, &item)
	}

	nextToken := ""
	if len(items) == findLimitUser {
		nextOffset := offset + findLimitUser
		nextToken = base64.StdEncoding.EncodeToString([]byte(fmt.Sprintf("%d", nextOffset)))
	}

	return items, &nextToken, nil
}
